### ISSUE TITLE
Unable to build vite project when applying `@sentry/vite-plugin`

### ISSUE THREAD

**Issue by larrifax** [getsentry/sentry-javascript-bundler-plugins#140]
I'm unable to build my vite + ts + vue project due to what seems to be some ESM related issue.
See reproduction and "Actual result" section below for further details.

### Environment

See reproduction

### Steps to Reproduce

Reproduction at https://stackblitz.com/edit/vitejs-vite-cupjlj?file=vite.config.ts

### Expected Result

What you thought would happen.

### Actual Result

Locally in my own project:

> failed to load config from /workspaces/app/vite.config.ts
error during build:
TypeError: sentryVitePlugin is not a function
    at file:///workspaces/way-app/vite.config.ts.timestamp-1669634829752.mjs:13:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadConfigFromBundledFile (file:///workspaces/way-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62832:21)
    at async loadConfigFromFile (file:///workspaces/way-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62717:28)
    at async resolveConfig (file:///workspaces/way-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62341:28)
    at async doBuild (file:///workspaces/way-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45248:20)
    at async build (file:///workspaces/way-app/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45237:16)
    at async CAC.<anonymous> (file:///workspaces/way-app/node_modules/vite/dist/node/cli.js:756:9)

In reproduction:

> $ vue-tsc && vite build
failed to load config from /home/projects/vitejs-vite-cupjlj/vite.config.ts
error during build:
Error: _file_home_projects_vitejs_vite_cupjlj_node_modules_sentry_vite_plugin_dist_cjs_index_js.default is not a function
    at file:///home/projects/vitejs-vite-cupjlj/vite.config.ts.timestamp-1669635121082.mjs
    at async doBuild (file://file:///home/projects/vitejs-vite-cupjlj/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45295:20)
    at async build (file://file:///home/projects/vitejs-vite-cupjlj/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45284:16)
    at async CAC.eval (file://file:///home/projects/vitejs-vite-cupjlj/node_modules/vite/dist/node/cli.js:767:9)

**Comment by lforst** [comment]
Thanks for reporting this and providing a reproduction example! I think we figured out what the problem was and will release a patch shortly!

**Comment by lforst** [comment]
We just released version `0.2.2` of the plugin which should resolve this. Let us know if it worked!

**Comment by larrifax** [comment]
`0.2.2` seems to have fixed this issue, but surfaced another one. This time around, the error is:

> 'default' is not exported by node_modules/localforage/dist/localforage.js, imported by node_modules/@sentry/integrations/esm/offline.js
file: /workspaces/way-app/node_modules/@sentry/integrations/esm/offline.js:2:0
1: import { getGlobalObject, logger, uuid4, normalize } from '@sentry/utils';
2: import localForage from 'localforage';
   ^
3: 
4: /**
error during build:
Error: 'default' is not exported by node_modules/localforage/dist/localforage.js, imported by node_modules/@sentry/integrations/esm/offline.js
    at error (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at ChildScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ClassBodyScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at FunctionScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at MemberExpression.bind (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:8601:49)

**Comment by lforst** [comment]
> `0.2.2` seems to have fixed this issue, but surfaced another one. This time around the error is:
> 
> > 'default' is not exported by node_modules/localforage/dist/localforage.js, imported by node_modules/@sentry/integrations/esm/offline.js
> > file: /workspaces/way-app/node_modules/@sentry/integrations/esm/offline.js:2:0
> > 1: import { getGlobalObject, logger, uuid4, normalize } from '@sentry/utils';
> > 2: import localForage from 'localforage';
> > ^
> > 3:
> > 4: /**
> > error during build:
> > Error: 'default' is not exported by node_modules/localforage/dist/localforage.js, imported by node_modules/@sentry/integrations/esm/offline.js
> > at error (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
> > at Module.error (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
> > at Module.traceVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
> > at ModuleScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
> > at ChildScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
> > at ClassBodyScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
> > at ChildScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
> > at FunctionScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
> > at ChildScope.findVariable (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
> > at MemberExpression.bind (file:///workspaces/way-app/node_modules/rollup/dist/es/shared/rollup.js:8601:49)

Yeah that seems to be related to #142
