### ISSUE TITLE
@sentry/vite-plugin 0.5.0 breaks react build

### ISSUE THREAD

**Issue by SteinRobert** [getsentry/sentry-javascript-bundler-plugins#194]
### Environment

@sentry-vite 0.5.0

### Steps to Reproduce

1. Bumped @sentry/vite-plugin from 0.4.0 to 0.5.0
2. Build react app
3. 
```
#22 5.795 "default" is not exported by "node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js", imported by "node_modules/@sentry/react/esm/profiler.js".
#22 5.795 file: /ui/node_modules/@sentry/react/esm/profiler.js:3:0
#22 5.795 1: import { getCurrentHub } from '@sentry/browser';
#22 5.795 2: import { timestampWithMs } from '@sentry/utils';
#22 5.795 3: import hoistNonReactStatics from 'hoist-non-react-statics';
#22 5.795    ^
#22 5.795 4: import * as React from 'react';
#22 5.795 5: import { REACT_MOUNT_OP, REACT_UPDATE_OP, REACT_RENDER_OP } from './constants.js';
#22 5.797 error during build:
#22 5.797 RollupError: "default" is not exported by "node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js", imported by "node_modules/@sentry/react/esm/profiler.js".
```

### Expected Result

Successful compilation.

### Actual Result

-

**Comment by danawoodman** [comment]
Noticed the same issue in a SvelteKit project with the dependency `debug`. Spend hours trying to track it down as I couldn't imagine the Sentry plugin could have anything to do with it 🤦

**Comment by micah-redwood** [comment]
Also having builds fail (`vite build`) after upgrading from 0.4.0 to 0.5.0

```
vite v4.1.4 building for qa...
[sentry-vite-plugin] Info: Sending error and performance telemetry data to Sentry.
[sentry-vite-plugin] Info: To disable telemetry, set `options.telemetry` to `false`.
✓ 3473 modules transformed.
Cannot read properties of undefined (reading 'slice')
error during build:
TypeError: Cannot read properties of undefined (reading 'slice')
    at getCodeFrame (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:2013:65)
    at augmentCodeLocation (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:2122:28)
    at Module.addLocationToLogProps (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:13695:13)
    at Module.warn (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:13577:14)
    at resolveNamespaceVariables (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:9378:24)
    at MemberExpression.bind (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:9131:38)
    at CallExpression.bind (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:5726:23)
    at CallExpression.bind (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:9470:15)
    at ArrowFunctionExpression.bind (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:5726:23)
    at VariableDeclarator.bind (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:5726:23)
    at VariableDeclaration.bind (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:5722:28)
    at Program.bind (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:5722:28)
    at Module.bindReferences (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:13170:18)
    at Graph.sortModules (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:24505:20)
    at Graph.build (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:24389:14)
    at async file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:25406:13
    at async catchUnfinishedHookActions (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:24559:20)
    at async rollupInternal (file:///{edited}/node_modules/rollup/dist/es/shared/node-entry.js:25401:5)
    at async build (file:///{edited}/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44664:18)
    at async CAC.<anonymous> (file:///{edited}/node_modules/vite/dist/node/cli.js:813:9)
```

**Comment by lforst** [comment]
Hm, from looking at the errors you guys shared I have actually no clue what might be going wrong. Normally I have *some* guess 😄 Is anybody able to provide reproduction?

**Comment by lforst** [comment]
@danawoodman can you share the exact error?

**Comment by SteinRobert** [comment]
The sentry profiler does not work :) 
Yes:
https://github.com/gefyrahq/gefyra-docker-desktop-extension
1. Clone
2. ` cd ui/`
3. `npm ci`
4. `npm i @sentry/vite-plugin@0.5.0`
5. `npm run build`
6. See the error.

Here are the logs from the corresponding docker build:
https://github.com/gefyrahq/gefyra-docker-desktop-extension/actions/runs/4622457507/jobs/8175164100

**Comment by lforst** [comment]
@SteinRobert thanks for providing the reproduction! I was able to reproduce and have a fix cooking for a patch shortly!

**Comment by lforst** [comment]
We just released version `0.5.1` of the plugin. Let me know if it resolves the issue for you! Thanks for your help!

**Comment by danawoodman** [comment]
@lforst thanks for the quick fix!

**Comment by SteinRobert** [comment]
Works! 
https://github.com/gefyrahq/gefyra-docker-desktop-extension/actions/runs/4632228960/jobs/8196046379?pr=119
Thank you for the quick response and fix!

**Comment by lforst** [comment]
@SteinRobert Thank you for confirming!
