### ISSUE TITLE
require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by MathiasWP** [getsentry/sentry-javascript-bundler-plugins#211]
### Environment
`"@sentry/vite-plugin": "^0.7.1"`

### Steps to Reproduce
I followed the exact steps from https://docs.sentry.io/platforms/node/guides/connect/sourcemaps/uploading/vite/

### Expected Result
Project should build

### Actual Result
```bash
failed to load config from /Users/app/vite.config.ts
error when starting dev server:
ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///Users/@sentry/bundler-plugin-core/dist/esm/index.mjs:2121:32
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async loadConfigFromBundledFile (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-79892de8.js:63967:21)
    at async loadConfigFromFile (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-79892de8.js:63852:28)
    at async resolveConfig (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-79892de8.js:63466:28)
    at async createServer (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-79892de8.js:62752:20)
    at async CAC.<anonymous> (file:///Users/frontend/node_modules/vite/dist/node/cli.js:734:24)
```

**Comment by lforst** [comment]
Hey, can you check if this is an issue when downgrading the plugin to version `0.6.0`?

**Comment by henrik-d** [comment]
I have the same problem with 0.7.1. Version 0.6.0 is working though.

**Comment by lforst** [comment]
Alright we published another patch. Can you give it another go? This time with version `0.7.2`? :)

Also, I wanna encourage everybody to use the new `sourcemaps.assets` option. It should be much more resilient than the `include` option.

**Comment by henrik-d** [comment]
Wow, that was fast. For me this fixes the issue.

**Comment by lforst** [comment]
<img width="210" alt="Screenshot 2023-04-17 at 20 23 28" src="https://user-images.githubusercontent.com/8118419/232576361-c855c150-3449-420b-bf80-9e1bb3cf6d0f.png">

**Comment by MathiasWP** [comment]
I updated, but now I'm met with this error:

```bash
node:internal/errors:484 timing config:load:flatten Completed in 2ms
    ErrorCaptureStackTrace(err);
    ^

Error: spawn /Users/node_modules/@sentry/cli/sentry-cli ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /Users/node_modules/@sentry/cli/sentry-cli',
  path: '/Users/node_modules/@sentry/cli/sentry-cli',
  spawnargs: [ 'releases', 'propose-version' ],
  cmd: '/Users/node_modules/@sentry/cli/sentry-cli releases propose-version'
}
```

Any idea what triggers this error @lforst?

**Comment by lforst** [comment]
@MathiasWP did you happen to have Sentry CLI installed globally? Can you try uninstalling it, reinstalling the plugin and trying everything again?

**Comment by ChaseWindYoungs** [comment]
when I run  `npm install @sentry/vite-plugin --save-dev`,  it can't install in my project, waiting long time but nothing happend, what can I do ?

**Comment by lforst** [comment]
@ChaseWindYoungs commented in the issue you created: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/214#issuecomment-1515976546
