### ISSUE TITLE
esbuild plugin fails to create a release

### ISSUE THREAD

**Issue by happenslol** [getsentry/sentry-javascript-bundler-plugins#263]
### Environment

```
node v19.9.0
npm v9.6.3
esbuild v0.17.19
@sentry/esbuild-plugin v2.0.0
```

### Steps to Reproduce

I've created a minimal reproduction [here](https://github.com/happenslol/sentry-esbuild-issue-reproduction).

### Expected Result

A new release should be created and uploaded to sentry. The build should complete without issues.

### Actual Result

The build fails to resolve `_sentry-debug-id-injection-file` as well as `_sentry-release-injection-file`. From what I can see in the source [here](https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/packages/esbuild-plugin/src/index.ts), these should be added as virtual files that are retrieved using the `js` loader, but somehow they are not picked up.

Here's the full build log:

```
> node scripts/bundle.js

[sentry-esbuild-plugin] Info: Sending error and performance telemetry data to Sentry. To disable telemetry, set `options.telemetry` to `false`.
✘ [ERROR] Could not resolve "_sentry-debug-id-injection-file"

✘ [ERROR] Could not resolve "_sentry-release-injection-file"

2 errors
> Found 0 files
> Adding source map references
> Nothing to upload
/tmp/sentry-test/node_modules/esbuild/lib/main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
error: Could not resolve "_sentry-debug-id-injection-file"
error: Could not resolve "_sentry-release-injection-file"
    at failureErrorWithLog (/tmp/sentry-test/node_modules/esbuild/lib/main.js:1636:15)
    at /tmp/sentry-test/node_modules/esbuild/lib/main.js:1048:25
    at /tmp/sentry-test/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "_sentry-debug-id-injection-file"'
    },
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Could not resolve "_sentry-release-injection-file"'
    }
  ],
  warnings: []
}
```

**Comment by lforst** [comment]
Hm, this seems to be broken with the current version of esbuild. With `0.14.49` this still worked... Lemme see if I can fix this.

**Comment by happenslol** [comment]
Awesome, thank you!

**Comment by kholiavko-roman** [comment]
Hey guys. I am having the same issue after updating to `@sentry/vite-plugin` to v 2.2.0


```
1:53:32 PM [vite] Internal server error: Cannot find module 'sentry-release-injection-file'
```

`node -v v18.16.0`
`npm -v 9.5.1`
`esbuild --version 0.17.19`
`@sentry/vite-plugin": "2.2.0",`
` "vite": "^4.3.9",


but it works fine for me on `@sentry/esbuild-plugin v2.0.0`

**Comment by lforst** [comment]
@kholiavko-roman can you please open a new issue and share a reproduction example? Thanks!
