### ISSUE TITLE
`ERROR: Unexpected ";"` when using sentryVitePlugin

### ISSUE THREAD

**Issue by MathiasWP** [getsentry/sentry-javascript-bundler-plugins#298]
### Environment

Using: `"@sentry/vite-plugin": "^2.2.0"`
Framework: `"@sveltejs/kit": "1.20.0"`

This is the config i'm using for the plugin:

```ts
sentryVitePlugin({
	org: 'my-org',
	project: 'my-project',
	authToken: env.SENTRY_AUTH_TOKEN,
	sourcemaps: {
		ignore: ['node_modules', 'vite.config.ts'],
		// Specify the directory containing build artifacts
		assets: './.svelte-kit/**'
	}
})
```

### Steps to Reproduce

1. Built my project

### Expected Result

Build should complete with no syntax error. This has happened for over a week now. We use dependabot, so a new build runs every time the plugin gets an update.

### Actual Result

It seems like Sentry is injecting some code that causes a syntax error in the transformed code.

```bash
rendering chunks (46)...[vite:esbuild-transpile] Transform failed with 1 error:
chunks/navigation.js:49:38: ERROR: Unexpected ";"

Unexpected ";"
47 |   * @returns {void}
48 |   */
49 |  const afterNavigate = /* @__PURE__ */ ;!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="21ba7d35-8a1d-4997-1126-b7ce028af103",e._sentryDebugIdIdentifier="sentry-dbid-21ba7d35-8a1d-4997-1126-b7ce028af103")}catch(e){}}();client_method('after_navigate');
   |                                        ^
50 |  
51 |  export { afterNavigate as a, beforeNavigate as b };

✓ built in 11.84s
error during build:
Error: Transform failed with 1 error:
chunks/navigation.js:49:38: ERROR: Unexpected ";"
    at failureErrorWithLog (/tech/frontend/node_modules/esbuild/lib/main.js:1636:15)
    at /tech/frontend/node_modules/esbuild/lib/main.js:837:29
    at responseCallbacks.<computed> (/tech/frontend/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/tech/frontend/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/tech/frontend/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
```

**Comment by FredrikAugust** [comment]
This is currently preventing us from upgrading to the latest version as well.

**Comment by FredrikAugust** [comment]
We've used 2.0.0 without problems, so this occurred between those two versions.

**Comment by MathiasWP** [comment]
It seems like the injection of the sentry method will make SvelteKit crash even if the semicolon is removed properly. 

It would make the assignment go from:

```ts
export const afterNavigate = /* @__PURE__ */ client_method('after_navigate');
```

to 

```ts
const afterNavigate = /* @__PURE__ */ !function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="21ba7d35-8a1d-4997-1126-b7ce028af103",e._sentryDebugIdIdentifier="sentry-dbid-21ba7d35-8a1d-4997-1126-b7ce028af103")}catch(e){}}();client_method('after_navigate');
```

Refactored:

```ts
const sentryThing = !function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="21ba7d35-8a1d-4997-1126-b7ce028af103",e._sentryDebugIdIdentifier="sentry-dbid-21ba7d35-8a1d-4997-1126-b7ce028af103")}catch(e){}}()


const afterNavigate = /* @__PURE__ */ sentryThing; client_method('after_navigate');
```

It becomes clear that afterNavigate will now be assigned the value of the Sentry method instead of the `client_method('after_navigate')`.

**Comment by jdk2pq** [comment]
We have the exact same issue and error with a Vue 3 application. Strangely, we have no issues building the project locally, but when it gets built in our AWS CodeBuild CD environment, we see the error above.

**Comment by Woodii1998** [comment]
https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/295

We had the same problem and I spent a long time trying to reproduce it without success, and I suspect that the problem was related to the size of the project, as our project was very large

**Comment by MathiasWP** [comment]
> We have the exact same issue and error with a Vue 3 application. Strangely, we have no issues building the project locally, but when it gets built in our AWS CodeBuild CD environment, we see the error above, but with the [Maska](https://github.com/beholdr/maska) dependency
> 
> ```shell
> [vite:esbuild-transpile] Transform failed with 1 error:
> assets/maska-!~{01w}~.js:165:26: ERROR: Unexpected ";"
> 
> Unexpected ";"
> 163|    }
> 164|  }
> 165|  const v = /* @__PURE__ */ ;!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="{{ our project's Debug ID }}",e._sentryDebugIdIdentifier="{{ our project's Debug ID Identifier }}")}catch(e){}}();new WeakMap(), N = (n) => {
>    |                            ^
> 166|    setTimeout(() => {
> 167|      var t;
> 
> ✓ built in 23.37s
> error during build:
> Error: Transform failed with 1 error:
> assets/maska-!~{01w}~.js:165:26: ERROR: Unexpected ";"
>     at failureErrorWithLog (project/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1636:15)
>     at project/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:837:29
>     at responseCallbacks.<computed> (project/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:697:9)
>     at handleIncomingPacket (project/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:752:9)
>     at Socket.readFromStdout (project/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:673:7)
>     at Socket.emit (node:events:513:28)
>     at Socket.emit (node:domain:489:12)
>     at addChunk (node:internal/streams/readable:315:12)
>     at readableAddChunk (node:internal/streams/readable:289:9)
>     at Socket.Readable.push (node:internal/streams/readable:228:10)
>     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
> ·ELIFECYCLE· Command failed with exit code 1.
> ```

Notable observation is that this build also crashes around a `/* @__PURE__ */` comment

**Comment by lforst** [comment]
Thanks, everybody for helping troubleshoot this. I took a look but sadly still have a hard time reproducing. :(

My suspicion is that our matching logic for not injecting before file directives is faulty in very particular situations:

https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/013f7ff05ca95dcbdacff1b533fd533c02e44ef4/packages/bundler-plugin-core/src/index.ts#L343-L358

I tried various input values but could not reproduce behavior that puts the debug id snippet in the wrong place. What would really help I think is if we had the code of an output chunk (without the Sentry plugin) where this happens - I guess `chunks/navigation.js` in @MathiasWP's case.

**Comment by lforst** [comment]
Additional note: Can everybody triple-double check if they have both the `@sentry/vite-plugin` package and `@sentry/bundler-plugin-core` package on version 2.2.0 in their lockfile? Thanks.

**Comment by MathiasWP** [comment]
> Additional note: Can everybody triple-double check if they have both the `@sentry/vite-plugin` package and `@sentry/bundler-plugin-core` package on version 2.2.0 in their lockfile? Thanks.

Can confirm that we have version 2.2.0 for both the `@sentry/vite-plugin` package and `@sentry/bundler-plugin-core` package

**Comment by maggie9595** [comment]
> Additional note: Can everybody triple-double check if they have both the `@sentry/vite-plugin` package and `@sentry/bundler-plugin-core` package on version 2.2.0 in their lockfile? Thanks.

Confirmed that we (@jdk2pq) have 2.2.0 for both as well.

**Comment by lforst** [comment]
Can someone share the compiled code for a bundle that throws this error (when disabling the plugin)? Thanks!

**Comment by lforst** [comment]
Actually let's see if this is fixed before closing because I couldn't repro this

**Comment by MathiasWP** [comment]
> Thanks, everybody for helping troubleshoot this. I took a look but sadly still have a hard time reproducing. :(
> 
> My suspicion is that our matching logic for not injecting before file directives is faulty in very particular situations:
> 
> https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/013f7ff05ca95dcbdacff1b533fd533c02e44ef4/packages/bundler-plugin-core/src/index.ts#L343-L358
> 
> I tried various input values but could not reproduce behavior that puts the debug id snippet in the wrong place. What would really help I think is if we had the code of an output chunk (without the Sentry plugin) where this happens - I guess `chunks/navigation.js` in @MathiasWP's case.

Sorry, i did not see this message. Here's the content of the file that crashes (without the Sentry plugin enabled):

```ts
function client_method(key) {
  {
    if (key === "before_navigate" || key === "after_navigate") {
      return () => {
      };
    } else {
      const name_lookup = {
        disable_scroll_handling: "disableScrollHandling",
        preload_data: "preloadData",
        preload_code: "preloadCode",
        invalidate_all: "invalidateAll"
      };
      return () => {
        throw new Error(`Cannot call ${name_lookup[key] ?? key}(...) on the server`);
      };
    }
  }
}
const beforeNavigate = /* @__PURE__ */ client_method("before_navigate");
const afterNavigate = /* @__PURE__ */ client_method("after_navigate");
export {
  afterNavigate as a,
  beforeNavigate as b
};
//# sourceMappingURL=navigation.js.map
```

**Comment by lforst** [comment]
@MathiasWP thanks for providing this. Unfortunately I still can't reproduce it with the code 🤔

Let's see if the new version will fix this.

**Comment by jdk2pq** [comment]
@lforst sorry for the delay on this. I have a suspicion that it might be OS-dependent, because we were also unable to reproduce the issue on our Macs, but anytime our CodeBuild pipeline using Amazon Linux ran, we'd see the error. Haven't confirmed that yet though

**Comment by lforst** [comment]
> I have a suspicion that it might be OS-dependent, because we were also unable to reproduce the issue on our Macs, but anytime our CodeBuild pipeline using Amazon Linux ran, we'd see the error. Haven't confirmed that yet though

@jdk2pq that's also really interesting. I only tried on a mac so far. But I would be really surprised, since none of the logic here depends on OS specifics.

**Comment by jdk2pq** [comment]
> > I have a suspicion that it might be OS-dependent, because we were also unable to reproduce the issue on our Macs, but anytime our CodeBuild pipeline using Amazon Linux ran, we'd see the error. Haven't confirmed that yet though
> 
> @jdk2pq that's also really interesting. I only tried on a mac so far. But I would be really surprised, since none of the logic here depends on OS specifics.

Agreed, none of this logic should be OS-dependent, but the underlying `esbuild` binary would be different on each OS. Totally just a guess at this point, but I'm looking into it now.

**Comment by lforst** [comment]
We published version `2.2.1` maybe this fixes it.

**Comment by escherina** [comment]
It's also happening with version `2.1.0`. The error was in a different file, but again, the code injection causing failure was happening just after `*/` (sorry, can't share the file this time).

**Comment by 2snEM6** [comment]
> > Same is happening to me on `2.1.0` but with a slightly different syntax error: #306
> 
> @2snEM6 Just curious, is this happening locally for you and are you able to reproduce the issue? And if so, what OS are you using? Or is it only during CI/CD?

It is happening locally and in CI/CD. It does not matter if I do it in Docker with an Ubuntu image, with an Alpine image, or in my Mac machine

**Comment by jdk2pq** [comment]
> > > Same is happening to me on `2.1.0` but with a slightly different syntax error: #306
> > 
> > 
> > @2snEM6 Just curious, is this happening locally for you and are you able to reproduce the issue? And if so, what OS are you using? Or is it only during CI/CD?
> 
> It is happening locally and in CI/CD. It does not matter if I do it in Docker with an Ubuntu image, with an Alpine image, or in my Mac machine

@2snEM6 Thanks for confirming. I guess that means it's not OS-based with different `esbuild` binaries. I tried recreating the issue in Docker yesterday with our CodeBuild image and surprisingly couldn't reproduce it either.

**Comment by 2snEM6** [comment]
> > > > Same is happening to me on `2.1.0` but with a slightly different syntax error: #306
> > > 
> > > 
> > > @2snEM6 Just curious, is this happening locally for you and are you able to reproduce the issue? And if so, what OS are you using? Or is it only during CI/CD?
> > 
> > 
> > It is happening locally and in CI/CD. It does not matter if I do it in Docker with an Ubuntu image, with an Alpine image, or in my Mac machine
> 
> @2snEM6 Thanks for confirming. I guess that means it's not OS-based with different `esbuild` binaries. I tried recreating the issue in Docker yesterday with our CodeBuild image and surprisingly couldn't reproduce it either.

Since we can't wait for this to be fixed and unfortunately I can't help right now to pinpoint the issue :( I am basically calling `sentry-cli` and `sentry-cli` works. I assume the plugin doesn't use `sentry-cli` underneath? I can't understand how `sentry-cli` works but the plugin does not, or if the plugin does something different that I don't know of.

Anyway, I will try to isolate the file that is causing the issue so I can share a reproducible example. Thanks

**Comment by jdk2pq** [comment]
@lforst Here's a minimal reproduction for the issue: https://github.com/jdk2pq/sentry-vite-plugin-error Let me know if that works for you.

**Comment by jdk2pq** [comment]
> @lforst Here's a minimal reproduction for the issue: https://github.com/jdk2pq/sentry-vite-plugin-error Let me know if that works for you.
> 
> The trick seemed to be lazy-loading components with Vue Router so that each page component would be in its own chunk _and_ the Maska dependency would be in a separate chunk as well. Without lazy-loading the components for each route, vite would just make a single JS chunk and everything built fine.

Also, this should work for any OS, any environment. My initial guess that it was OS-dependent was wrong. And while my repro uses Maska to show the issue, I think we could replace that with any of the dependencies or code above and it'd still apply, as long as that code gets built into a separate chunk by vite.

**Comment by lforst** [comment]
@jdk2pq Yup that seems to be it. Thank you so much!

**Comment by MathiasWP** [comment]
please release

**Comment by lforst** [comment]
Please check out version `2.2.2` of the package which should have the fix for this issue!

**Comment by MathiasWP** [comment]
> Please check out version `2.2.2` of the package which should have the fix for this issue!

Thank you, that fixed it! Great work 🎉

**Comment by lforst** [comment]
Let's thank @jdk2pq for this :D
