### ISSUE TITLE
NextJS 13.4.10 - `TypeError: Cannot destructure property 'RawSource' of 'require(...)' as it is undefined`

### ISSUE THREAD

**Issue by LordSimal** [getsentry/sentry-javascript-bundler-plugins#346]
### Environment

A generic NextJS 13 app with `@sentry/nextjs` installed 

NodeJS 18.16.0
@sentry/nextjs 7.58.1
@sentry/webpack-plugin 2.4.0 

### Steps to Reproduce

Update `next` from 13.4.9 => 13.4.10

### Expected Result

No error happens after starting the dev environment with `npm run dev`

### Actual Result

After `npm run dev` this problem occurs

```
error TypeError: Cannot destructure property 'RawSource' of 'require(...)' as it is undefined.
    at @sentry/nextjs (MyAppPath/.next/server/app/page.js:22:18)
    at __webpack_require__ (MyAppPath/.next/server/webpack-runtime.js:33:43)
    at eval (./sentry.server.config.js:2:72)
    at (sc_server)/./sentry.server.config.js (MyAppPath/.next/server/app/page.js:11211:1)
    at __webpack_require__ (MyAppPath/.next/server/webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:6:82)
    at (sc_server)/./app/layout.tsx (MyAppPath/.next/server/app/page.js:9592:1)
    at Function.__webpack_require__ (MyAppPath/.next/server/webpack-runtime.js:33:43)
```

### Proposed solution

Changing 

```
const { RawSource } = require('webpack-sources');
```
to
```
const RawSource = require('webpack-sources');
```

inside `node_modules/@sentry/webpack-plugin/src/index.js` fixes the error but I haven't checked if all sentry functionality still works.

**Comment by JamesSingleton** [comment]
Yea just started getting this when I upgraded next to 13.4.10 😞

**Comment by LordSimal** [comment]
I can confirm that this error ist not present with `next` 13.4.9
So something inside that release triggers this error

**Comment by LordSimal** [comment]
For some reason doing another round of `npm update` now fixes the problem 🤷🏻
