### ISSUE TITLE
After upgrading @sentry/webpack-plugin from 1.2.0 to 2.4.0 I get ENOMEM stable

### ISSUE THREAD

**Issue by erictheswift** [getsentry/sentry-javascript-bundler-plugins#352]
### Environment

Debian-based jenkins-agent

### Steps to Reproduce

Upgraded @sentry/webpack-plugin from 1.2.0 to 2.4.0 and then on webpack build with sourcemaps upload started getting `spawn ENOMEM` error.
Ofc likely our agents should likely get more resources, but is a big change in memory consumption actually expected since @1.2.0?

My config change
```diff
-@1.2.0
-new SentryPlugin({
-  release: env.RELEASE,
-  include: outputDir,
-  project: _3,
-  org: _2,
-  authToken: _1,
-  errorHandler: _,
-})
+@2.4.0
+sentryWebpackPlugin({
+  authToken: _1,
+  org: _2,
+  project: _3,
+  release: { name: env.RELEASE },
+  sourcemaps: { assets: outputDir },
+  telemetry: false,
+  // < @sentry/webpack-plugin@2 mode:
+  //  uploadLegacySourcemaps: outputDir,
+}),
```
(also @sentry/* packages bump from 7.41.0 to 7.59.3, but I think that's not significant here)

Should I try falling back to `uploadLegacySourcemaps` mode? What is the implementation difference between sourcemaps: * and uploadLegacySourcemaps? Maybe my configuration is wrong?)
### Expected Result

Update goes fluently

### Actual Result

Got consistently:
```
{webpack} emitting
 Error: spawn ENOMEM
     at ChildProcess.spawn (node:internal/child_process:413:11)
     at spawn (node:child_process:757:9)
     at Object.execFile (node:child_process:348:17)
     at _/node_modules/@sentry/cli/js/helper.js:194:20
     at new Promise (<anonymous>)
     at Object.execute (_/node_modules/@sentry/cli/js/helper.js:182:10)
     at Releases.execute (_/node_modules/@sentry/cli/js/releases/index.js:262:19)
     at Releases.new (_/node_modules/@sentry/cli/js/releases/index.js:55:17)
     at _callee$ (file://_/node_modules/@sentry/bundler-plugin-core/src/plugins/release-management.ts:53:41)
     at tryCatch (file://_/node_modules/@sentry/bundler-plugin-core/dist/esm/index.mjs:81:17)
     at Generator.<anonymous> (file://_/node_modules/@sentry/bundler-plugin-core/dist/esm/index.mjs:162:22)
     at Generator.next (file://_/node_modules/@sentry/bundler-plugin-core/dist/esm/index.mjs:106:21)
     at asyncGeneratorStep (file://_/node_modules/@sentry/bundler-plugin-core/dist/esm/index.mjs:343:24)
     at _next (file://_/node_modules/@sentry/bundler-plugin-core/dist/esm/index.mjs:362:9)
     at file://_/node_modules/@sentry/bundler-plugin-core/dist/esm/index.mjs:367:7
     at new Promise (<anonymous>)
     at file://_/node_modules/@sentry/bundler-plugin-core/dist/esm/index.mjs:359:12
     at Object.writeBundle (file://_/node_modules/@sentry/bundler-plugin-core/src/plugins/release-management.ts:97:35)
     at file://_/node_modules/unplugin/dist/index.mjs:1410:22
     at Hook.eval [as callAsync] (eval at create (_/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (_/node_modules/tapable/lib/Hook.js:18:14)
     at _/node_modules/webpack/lib/Compiler.js:882:27
     at _/node_modules/neo-async/async.js:2818:7
     at done (_/node_modules/neo-async/async.js:3522:9)
     at Hook.eval [as callAsync] (eval at create (_/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
     at _/node_modules/webpack/lib/Compiler.js:736:33
     at _/node_modules/graceful-fs/graceful-fs.js:143:16
     at _/node_modules/graceful-fs/graceful-fs.js:61:14
     at FSReqCallback.oncomplete (node:fs:197:23) {
   errno: -12,
   code: 'ENOMEM',
   syscall: 'spawn'
 }
```

**Comment by lforst** [comment]
Thanks for reporting this. We do some medium resource-intensive stuff, but not at the location where the ENOMEM happens. Can you share how much ram you usually have available?

**Comment by lforst** [comment]
Also: You should either configure the `sourcemaps.assets` option or `uploadLegacySourcemaps` option. Both is overkill.

**Comment by lforst** [comment]
I don't think child processes will cause any problem. Overhead is rather minimal.

Now that I think of it _we are_ creating a lot of promises in one particular case depending on how many files are uploaded. Can you share how many output-files you usually generate when building?
