### ISSUE TITLE
SyntaxError: Named export 'GLOBSTAR' not found

### ISSUE THREAD

**Issue by mishaled** [getsentry/sentry-javascript-bundler-plugins#431]
### Environment

We are running version `^2.8.0`.
Once in a while, we start having persistent errors like this-
```
failed to load config from ***/vite.config.mjs
error during build:

import { GLOBSTAR } from 'minimatch';
         ^^^^^^^^
SyntaxError: Named export 'GLOBSTAR' not found. The requested module 'minimatch' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'minimatch';
const { GLOBSTAR } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

### Steps to Reproduce

We are building a Vite project and uploading sourcemaps to Sentry with the plugin.
The errors reproduce both locally and in our CI (jenkins).

### Expected Result

No error in the build process.

### Actual Result

An error reported.

**Comment by lforst** [comment]
Hm, I am not sure how I can reproduce this. Would you mind sharing a small reproduction example (repo we can pull or stackblitz or similar) so we can debug this?

**Comment by pirey** [comment]
hi @lforst this issue seems related to this one https://github.com/nodejs/node/issues/35893

the issue might be caused by
```
import { GLOBSTAR } from 'minimatch'
```

and can be resolved by change it to 
```
import minimatch from 'minimatch'
const { GLOBSTAR } = minimatch
```

**Comment by lforst** [comment]
@pirey none of that code is in our package. I wouldn't know how to change that tbh.

**Comment by Nikhil-Bhat6** [comment]
I had the same issue and noticed that we had a resolution/override set up for the minimatch version:

`"resolutions": {
  "minimatch": "3.0.5"
}`

Removing it or bumping it up resolved the error.

**Comment by huberemanuel** [comment]
@Nikhil-Bhat6 After applying your suggestion, I encountered the following error during the build process:

```
0.351 > vite build
0.351
0.508 failed to load config from /app/app/vite.config.js
0.508 error during build:
0.508 file:///app/app/node_modules/@sentry/bundler-plugin-core/node_modules/glob/dist/mjs/walker.js:7
0.508 import Minipass from 'minipass';
0.508        ^^^^^^^^
0.508 SyntaxError: The requested module 'minipass' does not provide an export named 'default'
0.508     at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
0.508     at async ModuleJob.run (node:internal/modules/esm/module_job:229:5)
0.508     at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
0.508     at async loadConfigFromBundledFile (file:///app/app/node_modules/vite/dist/node/chunks/dep-CHZK6zbr.js:66866:15)
0.508     at async loadConfigFromFile (file:///app/app/node_modules/vite/dist/node/chunks/dep-CHZK6zbr.js:66707:24)
0.508     at async resolveConfig (file:///app/app/node_modules/vite/dist/node/chunks/dep-CHZK6zbr.js:66307:24)
0.508     at async build (file:///app/app/node_modules/vite/dist/node/chunks/dep-CHZK6zbr.js:65395:18)
0.508     at async CAC.<anonymous> (file:///app/app/node_modules/vite/dist/node/cli.js:829:5)
```

Have you run into this issue as well?
